// Country list for dropdowns. Kept intentionally broad but manageable.
// Countries with explicit pricing appear in the pricing table (see pricing.ts).

export const COUNTRIES: string[] = [
  "United States",
  "United Kingdom",
  "England",
  "Australia",
  "China",
  "Kenya",
  "Uganda",
  "Tanzania",
  "Nigeria",
  "Somalia",
  "Burundi",
  "Canada",
  "Germany",
  "France",
  "India",
  "South Africa",
  "Ghana",
  "Rwanda",
  "Ethiopia",
  "Egypt",
  "Brazil",
  "Mexico",
  "Spain",
  "Italy",
  "Netherlands",
  "Sweden",
  "Norway",
  "Ireland",
  "New Zealand",
  "Japan",
  "South Korea",
  "Singapore",
  "United Arab Emirates",
  "Saudi Arabia",
  "Pakistan",
  "Bangladesh",
  "Philippines",
  "Indonesia",
  "Zimbabwe",
  "Zambia",
  "Malawi",
  "Mozambique",
  "Cameroon",
  "Senegal",
  "Morocco",
  "Other",
];
